version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      networks:
      -webnet
    restart: always
  redis:
    image: redis
    restart: always


